version: '3.8'

networks:
  shareit-network:
    driver: bridge

services:
  gateway:
    build: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: http://server:8080
      TZ: Europe/Moscow
    depends_on:
      - postgres
      - server
    networks:
      - shareit-network

  server:
    build: server
    container_name: server
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      TZ: Europe/Moscow
    depends_on:
      - postgres
    networks:
      - shareit-network

  postgres:
    image: postgres:14.12
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Europe/Moscow
    networks:
    - shareit-network